[build-system]
requires = ["setuptools", "wheel", "scikit-build", "cmake", "ninja", "setuptools-scm>=6.2", "pygccxml==2.4.0", "castxml==0.4.5", "pybind11-stubgen"]
[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
# Add to get all the output of the tests
#   "-s",
]
minversion = "6.0"
testpaths = [
    "python/kwiver/vital/tests",
    "tools/demo_python_impl_call.py",
    "python/kwiver/tools/tests",
]
